name: SDK Version Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo run -p sdk-version --target x86_64-unknown-linux-gnu