name: simconnect-sys
on: 
  workflow_dispatch:
  push:
    paths:
      - 'simconnect-sys/**'
  pull_request:
    paths:
      - 'simconnect-sys/**'

jobs:

  test:
    name: cargo test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build -F vendored
      - run: cargo test -F vendored -p simconnect-sys

  dryrun:
    name: cargo publish --dry-run
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo publish -F vendored -p simconnect-sys --dry-run 